name: firebase_auth_oauth_platform_interface
description: Platform interface plugin for firebase_auth_oauth. This includes
  API definition which will be implemented for android, ios and web.
version: 1.0.2
homepage: https://github.com/amrfarid140/firebase_auth_oauth/tree/master/firebase_auth_oauth_platform_interface

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
